<?php

########################################################################
# Extension Manager/Repository config file for ext: "turnjs"
#
# Auto generated by Extension Builder 2012-11-10
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'turnjs',
	'description' => 'turn.js is a flipbook framework build on HTML5. See all about turn.js on www.turnjs.com
		This extension implements turn.js for whole TYPO3 pages',
	'category' => 'plugin',
	'author' => 'hmmh Team TYPO3',
	'author_email' => 'typo3@hmmh.de',
	'author_company' => 'hmmh multimediahaus AG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>